services:
  mariadb:
    build:
      context: srcs/requirements/mariadb
      dockerfile: Dockerfile
    volumes: [ mariadb-volume:/var/lib/mysql ]
    networks: [ inception ]
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-"wordpress"}
      MYSQL_USER: ${MYSQL_USER:-"wordpress"}
    secrets: [ mysql_password, mysql_root_password ]
  php:
    build:
      context: srcs/requirements/php
      dockerfile: Dockerfile
    volumes: [ www-volume:/var/www/html ]
    networks: [ inception ]
    restart: always
    depends_on: [ mariadb ]
  nginx:
    build:
      context: srcs/requirements/nginx
      dockerfile: Dockerfile
    volumes: [ www-volume:/var/www/html ]
    networks: [ inception ]
    restart: always
    ports: [ 443:443, 80:80 ]
    depends_on: [ php ]
volumes:
  www-volume:
    name: inception-www
    driver: local
    driver_opts:
      device: ~/data/www
      o: bind
      type: none
  mariadb-volume:
    name: inception-mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none
networks:
  inception:
    name: inception
secrets:
  mysql_password:
    file: secrets/db_password.txt
  mysql_root_password:
    file: secrets/db_root_password.txt
