services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes: [mariadb-volume:/var/lib/mysql]
    networks: [inception]
    restart: always
  php:
    container_name: php
    build:
      context: ./requirements/php
      dockerfile: Dockerfile
    volumes: [www-volume:/var/www/html]
    networks: [inception]
    restart: always
    depends_on: [mariadb]
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes: [www-volume:/var/www/html]
    networks: [inception]
    restart: always
    ports: [443:443, 80:80]
    depends_on: [php]
volumes:
  www-volume:
    name: inception-www
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none
  mariadb-volume:
    name: inception-mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none
networks:
  inception:
    name: inception
